language: java
jdk: oraclejdk8
script: mvn test
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c9d15c7671aea65b9d29
    on_success: change
    on_failure: always
    on_start: never
